2 css
ArinaVerz/dz-arina pull request #2
Opened 2023-12-27 22:59 UTC by ArinaVerz

2023-12-29 08:17 UTC, Levitinn requested changes
не вижу подключенных файлов стилей, в файлах .html, соответственно и сами стили не применяются

2023-12-29 08:17 UTC, Levitinn commented on 1-blog/styles/CSS Selectors (blog).css
некорректное имя файла.  если это основной файл стилей для страницы, его стоит назвать index.css
а так же, нельзя использовать в названии файла кириллицу. только латиница

2023-12-29 08:17 UTC, Levitinn commented on 1-blog/styles/CSS Selectors (blog).css
html файлы должны придерживаться тех же правил наименования

2023-12-29 20:58 UTC, ArinaVerz commented on 1-blog/styles/CSS Selectors (blog).css
Здравствуйте! Подскажите, как подключить файлы стилей? Нужно отправить .html файлы в дополнение, в которых link stylesheet?

2024-01-08 19:28 UTC, Levitinn commented on 1-blog/styles/CSS Selectors (blog).css
прочти вот эту статью. если останутся вопросы - пиши)

2024-01-08 19:29 UTC, Levitinn requested changes
Нужно внести исправления по моим комментариям

2024-01-08 20:11 UTC, ArinaVerz commented on 1-blog/styles/CSS Selectors (blog).css
Статью не вижу(

2024-01-08 20:13 UTC, Levitinn commented on 1-blog/styles/CSS Selectors (blog).css
https://doka.guide/js/array-from/

2024-01-08 20:28 UTC, ArinaVerz commented on 1-blog/styles/CSS Selectors (blog).css
Извините, а вы уверены, что это мне? Я в этой статью ничего не понимаю.

2024-01-08 20:29 UTC, Levitinn commented on 1-blog/styles/CSS Selectors (blog).css
> Извините, а вы уверены, что это мне? Я в этой статью ничего не понимаю.

да, извиняюсь, не та статья)) 
https://timeweb.com/ru/community/articles/kak-pravilno-podklyuchit-css-k-html

2024-01-08 20:37 UTC, ArinaVerz commented on 1-blog/styles/CSS Selectors (blog).css
Спасибо большое! Это у меня всё сделано. Я файлы css подключила к файлам html, например, вот так:  <link rel="stylesheet" href="./styles/CSS Selectors (blog).css" />. Вопрос: чтобы вы могли просмотреть применение стилей, мне нужно вам отправить файлы css и файлы html, к которым подключены css? 
Ваше замечание: "не вижу подключенных файлов стилей, в файлах .html, соответственно и сами стили не применяются".

2024-01-08 20:38 UTC, ArinaVerz commented on 1-blog/styles/CSS Selectors (blog).css
Например вот так  <link rel="stylesheet" href="./styles/CSS Selectors (blog).css" />

2024-01-08 20:39 UTC, ArinaVerz commented on 1-blog/styles/CSS Selectors (blog).css
<link rel="stylesheet" href

2024-01-08 21:00 UTC, ArinaVerz commented on 1-blog/styles/CSS Selectors (blog).css
> некорректное имя файла. если это основной файл стилей для страницы, его стоит назвать index.css а так же, нельзя использовать в названии файла кириллицу. только латиница

А можно мне именовать файлы по наименованию уроков? Например: Selectors.css Blochnaya model.css и так далее?

2024-01-09 17:33 UTC, Levitinn commented
![image](https://github.com/ArinaVerz/dz-arina/assets/44999446/8f65eda9-c4d3-4e95-a4e9-c5663effcbda)
- файлы нельзя называть русскими буквами.
- слишком много файлов стилей. одного достаточно
- стили не применяются к странице

2024-01-09 17:34 UTC, Levitinn commented on 1-blog/index.html
> +                    <li> <a href="#">Мой блог</a></li>
пропал предлог "В"

2024-01-09 17:34 UTC, Levitinn commented on 1-blog/styles/styles-blog.css
> +    margin: 0 0 30px 0;
отступы справа и слева не нужны. выровнять текст по центру можно с помощью text-align: center

2024-01-09 17:41 UTC, Levitinn requested changes

2024-01-09 17:41 UTC, Levitinn commented on 1-blog/styles/styles-blog.css
> +    height: 76px;
высоту и ширину задавать не нужно. она складывается из размера шрифта текста и высоты строки

2024-01-09 17:41 UTC, Levitinn commented on 1-blog/styles/styles-blog.css
> +    height: 76px;
в других стилях так же высоту и ширину нужно убрать

2024-01-09 17:41 UTC, Levitinn commented on 1-blog/index.html
> +                <p id="name">Наталья Васильева</p>
не нужно использовать id для обращения к элементам, для этого есть классы

2024-01-09 17:41 UTC, Levitinn commented on 1-blog/index.html
> +                    <img src="C:/Users/emiro/Downloads/Rectangle%20181.svg" alt="Изображение монитора и компьютера на оранжевом фоне" />
нужно указывать относительный путь к картинке. у тебя указан путь к файлу, где он лежит на твоем компьютере. у меня например такой путь никуда не приведет, потому картинка не отрисуется

2024-01-09 17:41 UTC, Levitinn commented on 1-blog/styles/Blochnaya model.css
лишний файл

2024-01-09 17:41 UTC, Levitinn commented on 1-blog/styles/CSS Selectors (blog).css
лишний файл

2024-01-09 17:41 UTC, Levitinn commented on 1-blog/styles/Selectors.css
лишний

2024-01-09 17:41 UTC, Levitinn commented on 1-blog/styles/Блочная модель.css
лишний

2024-01-09 17:41 UTC, Levitinn commented on 2-Form/index.html
некорректные отступы

2024-01-09 21:16 UTC, ArinaVerz commented
> ![image](https://private-user-images.githubusercontent.com/44999446/295289380-8f65eda9-c4d3-4e95-a4e9-c5663effcbda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MzQ4NDMsIm5iZiI6MTcwNDgzNDU0MywicGF0aCI6Ii80NDk5OTQ0Ni8yOTUyODkzODAtOGY2NWVkYTktYzRkMy00ZTk1LWE0ZTktYzU2NjNlZmZjYmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDIxMDkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMDIzY2MwNjU4YmFhYTY5MGEzNmRhYWFjMzg1YmViMGQwMzE4MWMyMWNjMjEyMDJhOTEyNTZlZmM4NmNkM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1BRqDL7WjY6Rtny1jss8uvj4kSlt6y9RkRaPtDvGIfQ)
> 
> * файлы нельзя называть русскими буквами.
> * слишком много файлов стилей. одного достаточно
> * стили не применяются к странице

Здравствуйте! Не смогла, к сожалению, удалить здесь лишние файлы. Пыталась. Для проверки только: 1) В папке 1-blog: styles-blog.css, index.html; 2) В папке 2-Form: styles-form.css, index.html. В этих файлах должны применяться стили. Внесу исправления в эти файлы и отправлю на проверку.

2024-01-09 21:21 UTC, ArinaVerz commented on 1-blog/index.html
> +                <p id="name">Наталья Васильева</p>
> не нужно использовать id для обращения к элементам, для этого есть классы

Подскажите, если имеется один элемент, который отличный по своим параметрам от остальных, то для него тоже нужно использовать class? В каких случаях тогда использовать id?

2024-01-15 16:14 UTC, Levitinn requested changes
![image](https://github.com/ArinaVerz/dz-arina/assets/44999446/71eb0943-6765-430c-a3a3-855dd1db95ad)
- картинки не отображаются (некорректный путь)
- нет изображения девушки

2024-01-15 16:14 UTC, Levitinn commented on 1-blog/index.html
> +                    <li> <a href="#">Мой блог</a></li>
не исправлено

2024-01-15 16:14 UTC, Levitinn commented on 1-blog/index.html
> +                <p class="text2">
text2 и text3 имеют одинаковые стили, потому им нужно дать один единственный класс. нижний отступ у text3 нужно убрать, так как это не его отступ, а у футера

2024-01-15 16:14 UTC, Levitinn commented on 1-blog/index.html
> +                <h1>Теория цвета – Как влияет на поведение потребителей</h1>
отсутствует изображение девушки

2024-01-15 16:14 UTC, Levitinn commented on 1-blog/index.html
> +                    <img src="images/Rectangle 181.png" alt="Изображение монитора и компьютера на оранжевом фоне" />
некорректный путь до картинки, она не отображается

2024-01-15 16:14 UTC, Levitinn commented on 1-blog/index.html
> +                <h1>Теория цвета – Как влияет на поведение потребителей</h1>
не исправлено

2024-01-15 16:14 UTC, Levitinn commented on 2-Form/index.html
> +                    <label for="my company">Имя</label>
н а каждый инпут+ лейбл отдельный див нужен

2024-01-27 19:07 UTC, Levitinn requested changes

2024-01-27 19:07 UTC, Levitinn commented on 1-blog/index.html
> +                            <img src="images/LogoB.svg" alt="Логотип">
это не логотип, а часть ссылки "В мой блог"

2024-01-27 19:07 UTC, Levitinn commented on 1-blog/index.html
> +            <input type="text" id="Поиск" name="Поиск" placeholder="Поиск">
инпут нужно оборачивать в див

2024-01-27 19:07 UTC, Levitinn commented on 1-blog/index.html
> +                <p class="heroP">FRONTEND
некорректное название класса

2024-01-27 19:07 UTC, Levitinn commented on 1-blog/index.html
> +                    <img src="images/Devushka.svg" alt="Логотип">
некорректная картинка.

2024-01-27 19:07 UTC, Levitinn commented on 1-blog/styles/styles-blog.css
> +    margin: 0 0 77px 0;
не марджин, а паддинг

2024-01-29 17:45 UTC, Levitinn requested changes

2024-01-29 17:45 UTC, Levitinn commented on 1-blog/index.html
> +                    <li class="B"> <a href="#">В</a></li>
"В мой блог" это один элемент списка, который является ссылкой. Один, а не два раздельных элемента

2024-01-29 17:45 UTC, Levitinn commented on 1-blog/index.html
> +            <input type="text" id="Поиск" name="Поиск" placeholder="Поиск">
пробала табуляция. (вложенность). див и инпут стоят на одном уровне (в одном столбце)

2024-01-29 17:45 UTC, Levitinn commented on 1-blog/index.html
> +                <h1>Теория цвета – Как влияет на поведение потребителей</h1>
не исправлено

2024-01-29 17:45 UTC, Levitinn commented on 1-blog/index.html
> +                </div>
посмотри макет. часть контента в макете, отсутствует в верстке

2024-01-29 17:45 UTC, Levitinn commented on 1-blog/index.html
> +            <section>
не нужно все делать секциями, используй дивы

2024-01-29 20:17 UTC, ArinaVerz commented on 1-blog/index.html
> +                    <li class="B"> <a href="#">В</a></li>
Подскажите, как тогда сделать, чтобы именно "В" был выделен в этом тексте "В мой блог"? Если я "В" вставляю в одну ссылку c "Мой блог", тогда текст "Мой блог" перенимает свойства "В" (квадрат с серым фоном, где "В" белым цветом, бордер-радиус и и так далее)

2024-01-29 20:21 UTC, ArinaVerz commented on 1-blog/index.html
> +                </div>
Я сверила. Не нахожу отличий. 
![Снимок экрана (17)](https://github.com/ArinaVerz/dz-arina/assets/151970605/92b97d05-f8c2-41d1-8e4f-9499d4bdcb6f)

2024-01-29 20:23 UTC, ArinaVerz commented on 1-blog/index.html
> +                    <li class="B"> <a href="#">В</a></li>
![Снимок экрана (17)](https://github.com/ArinaVerz/dz-arina/assets/151970605/cb3da6cc-020b-47ee-890e-028978ccfa9c)

2024-01-29 20:25 UTC, ArinaVerz commented on 1-blog/index.html
> +                </div>
![Снимок экрана (19)](https://github.com/ArinaVerz/dz-arina/assets/151970605/bfb07852-2b73-4031-bf3c-4b3cfabae6c4)

2024-01-29 20:26 UTC, ArinaVerz commented on 1-blog/index.html
> +                </div>
Я сверила. Вроде бы всё на месте.

2024-01-29 20:27 UTC, ArinaVerz commented on 1-blog/index.html
> +                </div>
Обратите внимание, что класс heroP у меня изменён на date. Не понимаю, почему у вас он не отобразился.

2024-01-29 20:57 UTC, Levitinn commented on 1-blog/index.html
> +                </div>
имя картинки некорретное.   Devushka (1).svg такой картинки нет в папке images
сама картинка у тебя включает в себя текст ФИО+ должность. это не верно, текст нужно делать версткой

2024-01-29 20:58 UTC, Levitinn commented on 1-blog/index.html
> +                    <li class="B"> <a href="#">В</a></li>
`<li> <a href="#"><span class="icon">В</span>Мой блог</a></li>`

2024-01-30 16:17 UTC, Levitinn requested changes

2024-01-30 16:17 UTC, Levitinn commented on 1-blog/index.html
> +                    <li> <a href="#"> <span class="icon">В</span>B Мой блог</a></li>
посмотри внимательно, что получилось. у тебя две "В"

2024-01-30 16:17 UTC, Levitinn commented on 1-blog/index.html
> +                </div>
![image](https://github.com/ArinaVerz/dz-arina/assets/44999446/37ba7ad6-1d64-4b4f-b6e3-4fb2d9cf199d)
картинки по прежнему нет

2024-01-30 16:17 UTC, Levitinn commented on 1-blog/index.html
> +            <section>
это не секция

2024-02-01 10:56 UTC, ArinaVerz commented on 1-blog/index.html
> +            <section>
![Снимок экрана (20)](https://github.com/ArinaVerz/dz-arina/assets/151970605/dae366a2-f999-4518-b6e9-514602daec65)

2024-02-01 10:56 UTC, ArinaVerz commented on 1-blog/index.html
> +            <section>
Я убрала

2024-02-01 17:29 UTC, Levitinn requested changes

2024-02-01 17:29 UTC, Levitinn commented on 1-blog/index.html
> +                    <img src="images/Ellipse 1 (2).svg" alt="Девушка">
не отображаются обе.
![image](https://github.com/ArinaVerz/dz-arina/assets/44999446/ca87cc06-8349-4e1c-abb9-861b59db1169)
для того, чтобы твоя картинка отображалась, нужно выполнить следующие действия:
1. нужно указывать относительный путь (./images/.....)  обрати внимание на точку и слеш 
2. Следи за названиями картинок, не нужно допускать в них пробелов и лишних символов, в данном случае, назови просто avatar.png
3. Убедись, что картинка есть по данному пути. Сейчас обе картинки девушки имеют вот такие пути 

`<img src="images/Devushka.svg" alt="Девушка">
<img src="images/Group 7 (3).svg" alt="Девушка">`
но в самой папке images, файлов с таким именем нет
![image](https://github.com/ArinaVerz/dz-arina/assets/44999446/99769929-a550-432c-afb8-6e8ad4fc75a8)

2024-02-01 17:29 UTC, Levitinn commented on 1-blog/index.html
> +                    <img src="images/Ellipse 1 (2).svg" alt="Девушка">
помимо этого, необходимо внести правки по прошлым комментариям, где это не сделано)

2024-02-05 17:53 UTC, Levitinn requested changes

2024-02-05 17:53 UTC, Levitinn commented on 1-blog/index.html
> +                </div>
отлично! теперь нуно правильно поделить эту часть кода на "смысловые блоки"
смотри, мы имеем один блок в котором аватарка и текст (фио + должность) - это один цельный блок, назовем его, к примеру,  person (так же можем и назвать класс), а значит все это должно быть один див. далее, погружаемся ниже, внутрь этого person. там лежит картинка и контент. это еще два блока. иными словами внутри нашего person два дива, внутри первого имг, внутри второго еще два дива, один с ФИО, второй с должностью. 

примерно вот так, можно рассуждать пытаясь поделить страницу на условные смысловые блоки.

2024-02-05 17:53 UTC, Levitinn commented on 1-blog/styles/styles-blog.css
> +    margin: 80px 1020px 71px 226px;
эти марджины можно убрать, эти отступы должны быть у хедера, в виде паддинга (вертикальные), а горизонтальные (слева и справа) достигаются по средством дива с классом контейнер, Антон говорил об этом на уроке

2024-02-05 17:53 UTC, Levitinn commented on 1-blog/styles/styles-blog.css
> +    font-weight: 6px;
некорректный стиль. его надо убрать. и да, я тебя спутал вначале, в мой блог это логотип, не часть списка. вытащи его из нав и поставь перед ним. (ссылка в диве)

2024-02-05 17:53 UTC, Levitinn commented on 1-blog/styles/styles-blog.css
> +    margin: 0 0 69px 0;
это тоже некорректный стиль. ты дала всем дивам на странице отступ, а дивов у нас очень много. это свойство нужно убрать и добиться отступов другим путем, например, у дива с поиском отступа быть не должно, отступ снизу будет получен благодаря паддингу хедера, об этом я тебе сказал в другом комментарии

2024-02-05 17:53 UTC, Levitinn commented on 1-blog/styles/styles-blog.css
> +.text_date {
отступ должен быть не у параграфа, а у его обертки, если она есть. в твоем случае, она есть

2024-02-05 17:53 UTC, Levitinn commented on 1-blog/styles/styles-blog.css
> +    margin-left: 368px;
непонятный отступ. таких быть не должно. если хочешь что то выровнять и приходится задавать большой отступ, скорее всего, ты что то делаешь не так)))

2024-02-05 17:53 UTC, Levitinn commented on 1-blog/styles/styles-blog.css
> +    margin-bottom: 77px;
этот класс должен быть у футера, если он нужен ему. но точно не у потомка футера. в данном случае, отступ должен быть у самого футера, а не у этого параграфа

2024-02-05 17:53 UTC, Levitinn commented on 2-Form/index.html
> +            <footer>
футер здесь не нужен. чекбокс условий пользования относится непосредственно к форме

2024-02-07 18:22 UTC, Levitinn approved these changes
отступ параграфа поправь, ты не перенесла отступ к его диву родителю. (комментарий открытый)

2024-02-07 18:22 UTC, Levitinn commented on 1-blog/styles/styles-blog.css
> +    font-weight: 400;
это дефолтный вес шрифта, его указывать не нужно

2024-02-10 21:51 UTC, merged