3 flex
ArinaVerz/dz-arina pull request #4
Opened 2024-02-23 21:06 UTC by ArinaVerz

2024-02-24 12:09 UTC, Levitinn requested changes

2024-02-24 12:09 UTC, Levitinn commented on 1-blog/index.html
> +                <li class="item1"> <a href="#">Мой блог</a></li>
мой блог это часть логотипа вместе с "В"

2024-02-24 12:09 UTC, Levitinn commented on 1-blog/index.html
> +                <li class="item3"> <a href="#">Frontend</a></li>
у элементов списка не должно быть никаких отступов снизу

2024-02-24 12:09 UTC, Levitinn commented on 1-blog/index.html
>      <header class="wrapper_head">
потерялся отступ снизу

2024-02-24 12:09 UTC, Levitinn commented on 1-blog/index.html
> +                <li class="item3"> <a href="#">Frontend</a></li>
![image](https://github.com/ArinaVerz/dz-arina/assets/44999446/8555d548-7a38-4c0d-b0bf-b71031604d20)
девушка с текстом должна быть горизонтально расположена ( в одной "строке")

2024-02-24 12:09 UTC, Levitinn commented on 1-blog/index.html
image_main - не заданы максимальные размеры

2024-02-24 12:09 UTC, Levitinn commented on 1-blog/index.html
wrapper_text отступа снизу быть не должно. этот отступ должен быть верхним паддингом футера. А у футера нижний марджин должен быть его нижним паддингом

2024-02-25 21:40 UTC, ArinaVerz commented on 1-blog/index.html
+

2024-02-25 21:40 UTC, ArinaVerz commented on 1-blog/index.html
>      <header class="wrapper_head">
+

2024-02-25 21:41 UTC, ArinaVerz commented on 1-blog/index.html
> +                <li class="item3"> <a href="#">Frontend</a></li>
+

2024-02-25 21:51 UTC, ArinaVerz commented on 1-blog/index.html
> +                <li class="item1"> <a href="#">Мой блог</a></li>
+

2024-02-26 19:05 UTC, Levitinn commented on 1-blog/index.html
> +                <li class="item1"> <a href="#">Мой блог</a></li>
логотип не является элементом списка навигации по страниц. он должен быть отдельно. говоря "он", я имею ввиду и "В" и "мой блог"

2024-02-26 19:07 UTC, Levitinn commented on 1-blog/index.html
> +                <li class="item2"> <a href="#">HTML и CSS</a></li>
отступы между li лучше сделать через gap. если нет, то через марджин, но никак не паддинг. Паддинг это отступ ВНУТРЬ элемента, а марджин отступ ОТ ЭЛЕМЕНТА

2024-02-26 19:07 UTC, Levitinn commented on 1-blog/index.html
> +                <li class="item3"> <a href="#">Frontend</a></li>
текст не верно выровнен. он не должен быть отцентрован
![image](https://github.com/ArinaVerz/dz-arina/assets/44999446/c3a706f6-c504-4844-b6bd-53edb4ab2597)

2024-02-26 19:09 UTC, Levitinn commented on 1-blog/index.html
> +                <li class="item3"> <a href="#">Frontend</a></li>
и у картинки девушки не заданы макс размеры

2024-02-26 19:09 UTC, Levitinn commented on 1-blog/index.html
у текста есть левый и правый паддинг. это не верно. если нужно ограничить размер контента во всю ширину страницы следует использовать контейнер

2024-02-26 19:09 UTC, Levitinn commented on 1-blog/index.html
image_main не верно заданы максимальные размеры

2024-02-27 14:29 UTC, ArinaVerz commented on 1-blog/index.html
> +                <li class="item1"> <a href="#">Мой блог</a></li>
+

2024-02-27 14:29 UTC, ArinaVerz commented on 1-blog/index.html
> +                <li class="item3"> <a href="#">Frontend</a></li>
+

2024-02-27 18:55 UTC, ArinaVerz commented on 1-blog/index.html
> +                <li class="item2"> <a href="#">HTML и CSS</a></li>
+

2024-02-28 19:50 UTC, Levitinn commented on 1-blog/index.html
> +                <div class="wrapper_li">
есть логотип. есть панель навигации. у навигации есть три ссылки. и только эти ТРИ ССЫЛКИ могут считаться списком. каким образом у тебя внутри списка логотип который вообще никаким образом не связан по смыслу со списком навигации? логотип должен быть ВНЕ НАВИГАЦИИ. это отдельный компонент

2024-02-28 19:50 UTC, Levitinn commented on 1-blog/index.html
никаких изменений не вижу

2024-02-28 19:52 UTC, Levitinn commented on 1-blog/index.html
>      <header class="wrapper_head">
у хедера задан максимальная ширина. нужно исправить. макс ширина делается с помощью контейнера

2024-02-29 19:06 UTC, Levitinn commented on 1-blog/index.html
> +                <li class="item1"> <a href="#">Мой блог</a></li>
молодец. корректно вынесла логотип, однако, забыла, что он должен быть ссылкой, а не дивом)

2024-02-29 19:15 UTC, Levitinn commented on 1-blog/index.html
> +                <li class="item3"> <a href="#">Frontend</a></li>
Арина, смотри, когда есть изображение в верстке, твои действия должны быть следующими:
- оборачиваешь картинку в див и даешь диву класс
- смотришь по макету какие размеры должна занимать картинка, в случае с девушкой это width: 50px; height: 50px;
- значит, твое изображение должно быть максимум 50пх ширину и высоту. потому, ты задаешь диву-родителю (из первого пункта) следующие свойства 
![image](https://github.com/ArinaVerz/dz-arina/assets/44999446/b5ba08a0-0b82-4b14-8f2f-8c1e5524b4dd)
таким образом, твой див, в который обернуто изображение, всегда будет стараться занять максимальные разрешенные ему 50пх ширины и высоты
- теперь переходишь к самой картинке 
![image](https://github.com/ArinaVerz/dz-arina/assets/44999446/9c6afd4d-d8bf-4c45-b3ab-b5fe067d3def)
задав ей эти свойства, она всегда будет пытаться растянуться на максимально возможные размеры, которыми ее ограничивает ее див- обертка, а значит, если в будущем, ты или твой коллега, решит загрузить другую картинку, а она окажется размером меньше той, что была, твоя верстка не "поедет".

Придерживайся данному гайду всегда, когда видишь в верстке изображение, точно так же нужно сделать для изображения ноутбука и всех остальных (99% тех, что ты встретишь в будущем)

2024-03-03 15:11 UTC, Levitinn requested changes

2024-03-03 15:11 UTC, Levitinn commented on 1-blog/index.html
> +            <div class="wrapper_logo">
не так. ссылкой должен быть весь див wrapper_logo.

2024-03-04 08:21 UTC, Levitinn requested changes

2024-03-04 08:21 UTC, Levitinn commented on 1-blog/index.html
> +            <div class="wrapper_logo">
нет. wrapper_logo это же див самого логотипа, значит, он весь целиком и должен быть ссылкой. а сейчас посмотри, у тебя ссылка для иконки и ссылка для "мой блог". логотип один, а ссылки у тебя две. несостыковочка.  
сделай wrapper_logo ссылкой, а всех его потомков дивами

2024-03-05 20:41 UTC, merged